trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    # Install Pulumi
    curl -fsSL https://get.pulumi.com | sh
    # Export path for pulumi (assuming default installation path)
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi version

    # Install Nitric
    curl https://nitric.io/install | bash
    export PATH=$PATH:$HOME/.nitric/bin
    nitric --version
  displayName: 'Install Pulumi and Nitric'

