version: 2.1

executors:
  default-executor:
    docker:
      - image: circleci/node:14

jobs:
  install_dependencies:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Install Nitric CLI
          command: |
            curl https://nitric.io/install | bash
            export PATH=$PATH:$HOME/.nitric/bin

      - run:
          name: Install Pulumi CLI
          command: |
            curl -fsSL https://get.pulumi.com | sh
            export PATH=$PATH:$HOME/.pulumi/bin

  check_versions:
    executor: default-executor
    steps:
      - run:
          name: Check Nitric Version
          command: nitric version
      - run:
          name: Check Pulumi Version
          command: pulumi version

workflows:
  version: 2
  install_and_test:
    jobs:
      - install_dependencies
      - check_versions:
          requires:
            - install_dependencies
